spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GameStore_pg
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
gamestore:
      app:
        secret: fde09c8nh723dsaduoiasubpdiuvieeuiowu4eviouweoiuv5oipuweiovu5oipweu5oiv7eviopdrs7vo8
        lifetime: 60000000
        basedurl: http://localhost:8080
